name: nibuichi
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  convex_bottom_bar: ^3.2.0
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  firebase_database: ^11.0.4
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.3
  hooks_riverpod: ^2.5.1
  uuid: ^4.4.2
  cloud_firestore: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true