// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALLSFZiH6slJb5k64kkf-cI1GVdjoRInk',
    appId: '1:1076688965331:web:5c28bd7a10fde37bcbce26',
    messagingSenderId: '1076688965331',
    projectId: 'nibuichi-13ee2',
    authDomain: 'nibuichi-13ee2.firebaseapp.com',
    storageBucket: 'nibuichi-13ee2.appspot.com',
    measurementId: 'G-VZHLL5Y9WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV17r-aLS2_7WXtQEGO_d0vCjT1undfiw',
    appId: '1:1076688965331:android:28bce08b405dfeb5cbce26',
    messagingSenderId: '1076688965331',
    projectId: 'nibuichi-13ee2',
    storageBucket: 'nibuichi-13ee2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9nTCLAlXWo8fwLMicMMsc9AtO1iGW3YA',
    appId: '1:1076688965331:ios:2d8055a9cac47406cbce26',
    messagingSenderId: '1076688965331',
    projectId: 'nibuichi-13ee2',
    storageBucket: 'nibuichi-13ee2.appspot.com',
    iosBundleId: 'com.example.nibuichi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9nTCLAlXWo8fwLMicMMsc9AtO1iGW3YA',
    appId: '1:1076688965331:ios:2d8055a9cac47406cbce26',
    messagingSenderId: '1076688965331',
    projectId: 'nibuichi-13ee2',
    storageBucket: 'nibuichi-13ee2.appspot.com',
    iosBundleId: 'com.example.nibuichi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALLSFZiH6slJb5k64kkf-cI1GVdjoRInk',
    appId: '1:1076688965331:web:2f02d1293a7860cccbce26',
    messagingSenderId: '1076688965331',
    projectId: 'nibuichi-13ee2',
    authDomain: 'nibuichi-13ee2.firebaseapp.com',
    storageBucket: 'nibuichi-13ee2.appspot.com',
    measurementId: 'G-MBFM0C12V0',
  );
}
